### ISSUE TITLE
Google map

### ISSUE THREAD

**Issue by daphneeeee** [jeffrey0706/CloudNative_Fall2023_Team15#11]
- [ ] Show parking lot locations on the map
- [ ] Show parking lot detail after clicking the spot on the map
- [ ] Clicking "Reserve" can make a reservation and navigate to the reservation page

**Comment by Dobby-the-elf** [comment]
The implementation of this feature is handled locally. However, we have to synchronize the API_KEY credential file, given that this is a public repository.
