### ISSUE TITLE
Replace status string with int in response from /user_status endpoint

### ISSUE THREAD

**Issue by daphneeeee** [jeffrey0706/CloudNative_Fall2023_Team15#14]

**Comment by ander1119** [comment]
not sure what's this issue for? does status code refer to HTTP status code?

**Comment by ander1119** [comment]
from previous discussion, i only remember we decided to use int status for api **/user_status**, but im not sure this issue is related to it

**Comment by ander1119** [comment]
now in api **/user_status** we got enum for status
```
class Status(IntEnum):
    NONE = 0
    RESERVED = 1
    PARKED = 2
    EXPIRED = 3
```
