### ISSUE TITLE
What's the usage of `Message` in DELETE request

### ISSUE THREAD

**Issue by jeffrey0706** [jeffrey0706/CloudNative_Fall2023_Team15#6]
https://github.com/jeffrey0706/CloudNative_Fall2023_Team15/blob/6bfa318ae2bc58bbf953385502bb7a179d1c4aa8/backend/app/api/reservation_api.py#L74

Why do we need it?

**Comment by ander1119** [comment]
the message string contains detailed status when executing DELETE / GET command, one can check the request success or not by status code in response

200 -> success
404 -> car id not found or reservation not exist
503 -> some error happend when accessing / executing command in database
