### ISSUE TITLE
Need the info of whether there is any handicap or not

### ISSUE THREAD

**Issue by jeffrey0706** [jeffrey0706/CloudNative_Fall2023_Team15#8]
https://github.com/jeffrey0706/CloudNative_Fall2023_Team15/blob/6bfa318ae2bc58bbf953385502bb7a179d1c4aa8/backend/app/api/parkinglot_api.py#L19

We'll need the info of `priority`, which stores whether there is any handicap in the parking lot or not.

**Comment by ander1119** [comment]
now the response of **/parkinglots**  would be
`[
    {
        parkinglot_id: int,
        name: string,
        current_capacity: int,
        maximum_capacity: int,
        current_handicap_capacity: int,
        maximum_handicap_capacity: int,
    }
]`
